### PR TITLE
Only public post types will be selectable in the autocomplete Redirect To field

### LINKED ISSUE #331: Show publicly available post types in autocomplete dropdown for Redirect To
### Describe the bug

I discovered that the recenly merged feature has a regression: https://github.com/10up/safe-redirect-manager/pull/325

I see unexpected results in the dropdown. We should only display publicly available post types.

image
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bmarshall511**
### Description of the Change

Autocomplete will now only display public post types.

Closes #331

### How to test the Change

1. Go to add a new redirect page (/wp-admin/post-new.php?post_type=redirect_rule)
2. Start typing in the "Redirect To" field
3. Only public post types should be displayed

### Changelog Entry

> Fixed - Only public post types will be selectable in the autocomplete Redirect To field

### Credits

Props @bmarshall511 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by ravinderk — APPROVED** [review]

File: inc/classes/class-srm-post-type.php [hunk 1]
```diff
@@ -713,7 +713,11 @@ public function srm_autocomplete() {
 
 		$query = get_posts(
 			array(
-				'post_type'      => get_post_types(),
+				'post_type'      => get_post_types(
+					array(
+						'public' => true,
```
Comment (dkotter) [inline inc/classes/class-srm-post-type.php:718]: So I know this has already been merged in but I think the better approach here is to use the `is_post_type_viewable` function to filter the post types (see https://github.com/10up/distributor/pull/907/commits/4b8b77eb96135aa38324d134c01d7817def12437 and https://github.com/10up/distributor/pull/907#discussion_r922911937).

So something like:
```php
'post_type' => array_filter( get_post_types(), 'is_post_type_viewable' )
```

This checks for both the `public` argument and the `publicly_queryable` argument

Comment (ravinderk) [reply inc/classes/class-srm-post-type.php:718]: Existing query:
image


@dkotter I am getting the following result with the above code.
I think `redirect_rule` should not display in the list.

What do you think?

image

Comment (dkotter) [reply inc/classes/class-srm-post-type.php:718]: Yeah, doesn't make sense to show redirect rules within the redirect field. We can either unset that post type (see again Distributor: https://github.com/10up/distributor/pull/907/files#diff-a4c20b6d7391a224faf11e6161c80b408e2a0f5a71a92dc11b7eafe3cad83f94R320) or utilize the `is_post_type_viewable` core filter to remove the `redirect_rule` post type from showing (which would impact anyone else using this function, may or may not be a good thing)
