### PR TITLE
Bugfix: Issue 208 wildcard redirects

### LINKED ISSUE #136: Simple wildcard redirect not working as expected
I have some urls that I want to redirect to the homepage, they look like:
    /smile/
    /smile/page1/
    /smile/page2/
    /smile/page3/

I want to redirect the /smile/ and everything inside it to the homepage, so I would normally set up two redirect actions. One simple for the /smile/, and then a wildcard that redirects /smile/* to /.

However, when I visit /smile/page1/ I am redirected to /page1/

How can I fix this?

### LINKED ISSUE #156: Wildcard doesn't match zero characters
Given the following:

- Redirect From: `foo/*`
- Redirect To: `https://example.com/bar/*`

Results in:

1. `https://example.com/foo/baz` correctly redirects to `https://example.com/bar/baz`. i.e. `*` matches `baz`
2. `https://example.com/foo/` fails to redirect to the expected `https://example.com/bar/` i.e. `*` matches `{empty string}`.

The expected behaviour is that the wildcard could be an empty string.

The unit tests do NOT cover this use case.

The current workaround is to add a second redirect rule without the wildcard, which works:

- Redirect From: `foo/`
- Redirect To: `https://example.com/bar/`

### LINKED ISSUE #208: Redirecting with Wildcard to a Post Type Functions Differently After Updating Plugin
**Describe the bug**
I updated the plugin from version 1.9 to 1.9.3 and a redirect I setup with a wildcard now functions differently because of it. The wildcard was set up to redirect posts from one post type to another post type (after the post type was switched). I also have a main posts page with a similar path as the new post type.

**Steps to Reproduce**
1. Set up a post type that has **offer** as the parent path
1. Set up redirect from /resource/* to /offer/*
2. Set up a page with a /resources/ slug and make it your Posts page
3. Navigate to the /resources/ page and it brings you to a post within the resource post type (/resource/123), and not the /resources/ page

**Expected behavior**
The Resources (/resources/) post page should open. It does on version 1.9, but not on 1.9.3.

**Environment information**
 - Device: MacBook Pro in Lando/Pantheon local environment
 - OS: MacOS 10.15.4
 - Browser and version: Chrome 81.0.4044.129
 - WordPress version: 5.4.1
 - <details><summary>Site Health Info:</summary>

_Note: For privacy, I replaced client/author names/paths with ***_

   `
### wp-core ###

version: 5.4.1
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 7
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /app
wordpress_size: 146.41 MB (153520560 bytes)
uploads_path: /app/wp-content/uploads
uploads_size: 624.04 MB (654353483 bytes)
themes_path: /app/wp-content/themes
themes_size: 20.93 MB (21951017 bytes)
plugins_path: /app/wp-content/plugins
plugins_size: 40.39 MB (42348462 bytes)
database_size: 41.56 MB (43581440 bytes)
total_size: 873.33 MB (915754962 bytes)

### wp-active-theme ###

name: UnderStrap modified by *** (***)
version: 0.8.6
author: ***
author_website: ***
parent_theme: none
theme_features: automatic-feed-links, title-tag, menus, html5, post-thumbnails, customize-selective-refresh-widgets, post-formats, custom-background, custom-logo, infinite-scroll, jetpack-responsive-videos, jetpack-social-menu, woocommerce, wc-product-gallery-lightbox, wc-product-gallery-zoom, wc-product-gallery-slider, widgets, editor-style
theme_path: /app/wp-content/themes/***

### wp-themes-inactive (10) ###

Twenty Eleven: version: 2.3, author: the WordPress team (latest version: 3.4)
Twenty Fifteen: version: 1.4, author: the WordPress team (latest version: 2.6)
Twenty Fourteen: version: 1.6, author: the WordPress team (latest version: 2.8)
Twenty Nineteen: version: 1.0, author: the WordPress team (latest version: 1.5)
Twenty Seventeen: version: 1.0, author: the WordPress team (latest version: 2.3)
Twenty Sixteen: version: 1.0, author: the WordPress team (latest version: 2.1)
Twenty Ten: version: 2.1, author: the WordPress team (latest version: 3.0)
Twenty Thirteen: version: 1.7, author: the WordPress team (latest version: 3.0)
Twenty Twelve: version: 1.9, author: the WordPress team (latest version: 3.1)
Twenty Twenty: version: 1.2, author: the WordPress team

### wp-mu-plugins (11) ###

Core Custom Fields: version: 1.0, author: ***
Core Custom Post Types: version: 1.0, author: ***
Core Custom Taxonomies: version: 1.0, author: ***
Custom Fields Footer: version: 1.0, author: ***
Custom Fields Page Layouts: version: 1.0, author: ***
Custom Fields Page Layouts: version: 1.0, author: ***
Custom Fields Page Layouts: version: 1.0, author: ***
Custom Fields Sidebar: version: 1.0, author: ***
Pantheon: version: 0.1, author: Pantheon
Inbound Plugin: version: 1.0, author: ***
Resources / Offer Content Type: version: 1.0, author: ***

### wp-plugins-active (22) ###

Advanced Custom Fields: version: 5.8.9, author: Elliot Condon
Advanced Custom Fields: Flexible Content Field: version: 2.1.0, author: Elliot Condon
Advanced Custom Fields: Gallery Field: version: 2.1.0, author: Elliot Condon
Advanced Custom Fields: Options Page: version: 2.1.0, author: Elliot Condon
Advanced Custom Fields: Repeater Field: version: 2.1.0, author: Elliot Condon
Advanced Custom Fields: YouTube Field: version: 1.1.5, author: Hal Gatewood
Classic Editor: version: 1.5, author: WordPress Contributors
Contact Form 7: version: 5.1.7, author: Takayuki Miyoshi
Contact Form Submissions: version: 1.6.4, author: Jason Green
Duplicate Page: version: 4.2, author: mndpsingh287
Enable Media Replace: version: 3.3.12, author: ShortPixel
Force Strong Passwords: version: 1.8.0, author: Jason Cosper
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: version: 7.30.5, author: HubSpot
Limit Login Attempts: version: 1.7.1, author: Johan Eenfeldt
OptinMonster API: version: 1.9.6, author: OptinMonster Team
Reading Time WP: version: 2.0.9, author: Jason Yingling
Safe Redirect Manager: version: 1.9, author: 10up (latest version: 1.9.3)
Scalable Vector Graphics (SVG): version: 3.4, author: Sterling Hamilton
Simple Share Buttons Adder: version: 7.6.21, author: Simple Share Buttons
WP Version in Query String Modifier: version: 1.0.0.7, author: joesat
Yet Another Related Posts Plugin: version: 5.1.3, author: YARPP
Yoast SEO: version: 14.0.4, author: Team Yoast

### wp-plugins-inactive (14) ###

ACF Content Analysis for Yoast SEO: version: 2.3.0, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast
ACF to REST API: version: 3.2.0, author: Aires Gonçalves
Akismet Anti-Spam: version: 4.1.5, author: Automattic
Disable XML-RPC and Users REST endpoint: version: 1.0.0, author: ***
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Nested Pages: version: 3.1.10, author: Kyle Phillips
Post Types Order: version: 1.9.4.3, author: Nsp Code
Post Type Switcher: version: 3.2.0, author: John James Jacoby
Regenerate Thumbnails: version: 3.1.3, author: Alex Mills (Viper007Bond)
Show modified Date in admin lists: version: 1.1, author: Apasionados.es
WP REST API - Pure Taxonomies: version: 1.0, author: Andrew MAGIK
WP REST Filter: version: 1.4.3, author: SK8Tech

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 4
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.9.184-linuxkit x86_64
httpd_software: nginx/1.14.2
php_version: 7.3.12 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 120
memory_limit: 1G
max_input_time: 900
upload_max_size: 100M
php_post_max_size: 100M
curl_version: 7.52.1 OpenSSL/1.0.2t
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 10.1.43-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: https://***.lndo.site
WP_SITEURL: https://***.lndo.site
WP_CONTENT_DIR: /app/wp-content
WP_PLUGIN_DIR: /app/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 1G
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`
   </details>

### PR DESCRIPTION
**Pull request by amyevans**
### Description of the Change

Fixes #208.

This PR fixes a regression introduced in 1.9.3 that caused paths to match erroneously against a rule ending in `/*`.

### Alternate Designs

None.

### Benefits

* Improved handling for wildcard redirects.

### Possible Drawbacks

* Nothing immediately obvious, but there's perhaps the potential to break redirects in unforeseen scenarios not currently accounted for in test cases.

### Verification Process

* Added a test to address the case.
* Existing tests still pass.
* Tested within a project.

### Checklist:

- [X] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my change.
- [X] All new and existing tests passed.

### Applicable Issues

#208

### Changelog Entry

* Fixed: Regression related to wildcard matching

### CODE REVIEW

**Comment by jeffpaul** [comment]
@amyevans many thanks for the PR, its greatly appreciated!  We'll do a review on this and get back to you with any questions/concerns, but otherwise I've milestoned this for our next release.

File: tests/php/test-core.php [hunk 1]
```diff
@@ -564,6 +564,29 @@ function( $requested_path, $redirected_to, $status_code ) use ( &$redirect_to, &
...
+	public function testNoRedirectWildcard() {
+		$_SERVER['REQUEST_URI'] = '/one-page/';
+		$redirected             = false;
+		$redirect_to            = '/gohere';
+
+		// Create redirect for testing.
+		srm_create_redirect( '/one/*', $redirect_to );
+		add_action(
+			'srm_do_redirect',
+			function( $requested_path, $redirected_to, $status_code ) use ( &$redirect_to, &$redirected, &$expected ) {
```
Comment (dinhtungdu) [inline tests/php/test-core.php]: Can you explain why you pass `$redirect_to` and `$expected` here? I don't see the usage of these variables.

**Review by dinhtungdu — COMMENTED** [review]
Thank @amyevans so much! Tested and this PR worked as expected! I only have a question about the unit test. Otherwise, this one is looking good to me.

**Comment by picocodes** [comment]
I don't know if this is related,

but the following redirect rule `/guide/email-forms/*` => `/guide/getting-email-subscribers/*` redirects a request for "example.com/guide/email-forms/opt-in-forms-editor/" to "example.com/guide/getting-email-subscribersopt-in-forms-editor"

Notice the missing slash.

File: tests/php/test-core.php (hunk 1 above)
Comment (jeffpaul) [reply tests/php/test-core.php]: @amyevans are you able to explain those variables?

Comment (amyevans) [reply tests/php/test-core.php]: Good catch, they aren't used, just relics from copy/pasting another test as a starting point. I'll push up a new commit removing them.

**Comment by dinhtungdu** [comment]
@picocodes the issue you mentioned is fixed by this PR

**Review by dinhtungdu — APPROVED** [review]
LGTM 🎉
