### PR TITLE
Minor update to how autocomplete pulls public post types using is_post_type_viewable

### LINKED ISSUE #331: Show publicly available post types in autocomplete dropdown for Redirect To
### Describe the bug

I discovered that the recenly merged feature has a regression: https://github.com/10up/safe-redirect-manager/pull/325

I see unexpected results in the dropdown. We should only display publicly available post types.

image
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bmarshall511**
### Description of the Change

Minor update to how autocomplete pulls public post types using [is_post_type_viewable](https://developer.wordpress.org/reference/functions/is_post_type_viewable/), see https://github.com/10up/safe-redirect-manager/pull/332#discussion_r1248067118

Closes #331 

### How to test the Change

1. Go to add a new redirect page (/wp-admin/post-new.php?post_type=redirect_rule)
2. Start typing in the "Redirect To" field
3. Only public post types should be displayed

### Changelog Entry

> Fixed - Update to how post types are pulled in the autocomplete using is_post_type_viewable

### Credits

Props @bmarshall511, @dkotter 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: inc/classes/class-srm-post-type.php [hunk 1]
```diff
@@ -713,11 +713,7 @@ public function srm_autocomplete() {
 
 		$query = get_posts(
 			array(
-				'post_type'      => get_post_types(
-					array(
-						'public' => true,
-					)
-				),
+				'post_type'      => array_filter( get_post_types(), 'is_post_type_viewable' ),
```
Comment (dkotter) [inline inc/classes/class-srm-post-type.php]: As mentioned https://github.com/10up/safe-redirect-manager/pull/332#discussion_r1248088127, this will now show the `redirect_rule` post type, which doesn't really make sense in this context. I'd suggest either we `unset` that value or utilize the core `is_post_type_viewable` filter to remove it. Something like

```php
$post_types = array_filter( get_post_types(), 'is_post_type_viewable' );
unset( $post_types[ 'redirect_rule' ] );
```

**Review by dkotter — CHANGES_REQUESTED** [review]

File: inc/classes/class-srm-post-type.php (hunk 1 above)
Comment (bmarshall511) [reply inc/classes/class-srm-post-type.php]: @dkotter Right on! I've got it updated but used `array_filter` to remove that one. Let me know if you'd prefer the `unset` method instead.

**Review by dkotter — APPROVED** [review]
