### PR TITLE
Issue #366 - Make URL validation on input event instead of change event

### LINKED ISSUE #366: Redirect.js can leave publish button disabled when fields are valid
### Describe the bug

As the redirect.js file uses the `change` event to detect whether fields are valid, it requires users click out of the box before detecting the field has been filled out.

This can lead to confusion as the publish button remains disabled when the redirect fields have valid data, the user needs to click out of the field and then click the publish button.

This was reported in https://github.com/10up/safe-redirect-manager/issues/364#issuecomment-1939361111 (props @JosVelasco).

### Steps to Reproduce

1. Change the redirect status code to `301`
2. Click in to the redirect from to field
3. Type then delete some text
4. Click out of the redirect from field
5. The publish button should be disabled
6. Click in to the redirect from field
7. Type something, do NOT click out of the box
8. The publish button will remain disabled.

### Screenshots, screen recording, code snippet

_No response_

### Environment information

- Device: Macbook
- Browser: Firefox 122/macOS 12.7.3 

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by BhargavBhandari90**
### Description of the Change
Changed event for "Redirect From" field for URL validation.

- Previously it was on a `change` event, so validation was not happening unless we click out of the text field. Because of that publish button disabling was irregular and confusing.
- So made it on `keyup` event and added ajax abort to avoid simultaneous requests.
- Also added a typing wait time of 850 ms so when user stops typing, then URL validation will happen.
- Based on this validation process, disabling/enabling submit button became regular now.
- Also added a loding icon when user start typing, so that they know something is happening.

Video for better understanding for above bullet points https://somup.com/cZnTI6pzGz

Closes #366

### How to test the Change

- Go to WP admin --> Tools --> Safe Redirect Manager
- Click "Create Redirect Rule"
- Start typing into "Redirect From" and stop typing
- Remove some characters and stop
- Observe the submit button active/inactive state

### Credits
@BhargavBhandari90, @peterwilsoncc

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: assets/js/redirect.js [hunk 1]
```diff
@@ -3,26 +3,16 @@
...
-				if ( '1' === data ) {
-					$('#message').html( '' ).hide();
-					publishBtn.prop('disabled', false);
-				} else if ( '0' === data ) {
-					$('#message').html( `<p>${redirectValidation.urlError}</p>` ).show();
-				} else {
-					$('#message').html( `<p>${redirectValidation.fail.replace( '%s', data )}</p>` ).show();
-				}
-			});
+		fromRule.keyup(function(el) {
```
Comment (peterwilsoncc) [inline assets/js/redirect.js]:
```suggestion
		fromRule.on('input', function(el) {
```

I think the [`input`](https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event) event is better here as it describes the exact use case: 

> The input event fires when the value of an [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select), or [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) element has been changed as a direct result of a user action (such as typing in a textbox or checking a checkbox).

File: assets/js/redirect.js [hunk 2]
```diff
@@ -96,5 +86,40 @@
...
+			currentRequest = $.ajax({
+				url: window.ajaxurl,
+				method : 'GET',
+				data : {
+					action: 'srm_validate_from_url',
+					from: fromRule.val(),
+					_wpnonce: $('#srm_redirect_nonce').val()
+				},
+				beforeSend : function() {
+					if ( currentRequest != null ) {
```
Comment (peterwilsoncc) [inline assets/js/redirect.js]:
```suggestion
					if ( currentRequest !== null ) {
```

File: assets/js/redirect.js [hunk 3]
```diff
@@ -96,5 +86,40 @@
...
+						currentRequest.abort();
+					}
+				},
+				success: function( data ) {
+
+					// Remove loader.
+					if ( fromRule.hasClass( 'ui-autocomplete-loading' ) ) {
+						fromRule.removeClass( 'ui-autocomplete-loading' );
+					}
```
Comment (peterwilsoncc) [inline assets/js/redirect.js]:
```suggestion
					fromRule.removeClass( 'ui-autocomplete-loading' );
```

removeClass handles if the class doesn't exist so no need to check.

**Review by peterwilsoncc — COMMENTED** [review]
I've added a couple of notes inline, thanks for the pull request.

File: assets/js/redirect.js (hunk 1 above)
Comment (BhargavBhandari90) [reply assets/js/redirect.js]: Thank you for this. I've made this change now.

File: assets/js/redirect.js (hunk 2 above)
Comment (BhargavBhandari90) [reply assets/js/redirect.js]: Done

File: assets/js/redirect.js (hunk 3 above)
Comment (BhargavBhandari90) [reply assets/js/redirect.js]: Thank you for this. I've made this change now.

**Comment by BhargavBhandari90** [comment]
Thank you @peterwilsoncc for your suggestions.

**Comment by jeffpaul** [comment]
@peterwilsoncc back to you for review/approval/merging

**Review by Sidsector9 — APPROVED** [review]
Tests well 👍
